"use client";

/**
 * /developers — landing page for the API tier.
 *
 * Pitch: same JSON API that powers our frontend, exposed as a paid SaaS.
 * $99/mo target — high-margin because 1 developer = 1 sale, but we serve
 * 1 thin REST request not a full UI.
 *
 * Flow today: visitor lands here → reads docs → emails us / fills Tally
 * to get on waitlist → operator manually whitelists their email +
 * issues an API key. Once we hit ~10 dev users we wire automated
 * Stripe self-serve.
 */

import Link from "next/link";
import { ArrowRight, Code2, KeyRound, Sparkles } from "lucide-react";
import { useT } from "../lib/i18n";
import { BusRegisterExample } from "../components/PaperBacked";

const SAMPLE_PYTHON = `import requests, time

API = "https://trading-agents-platform.onrender.com"
TOKEN = "sk_xxx"  # request via /developers waitlist

# Kick off a decision job
job = requests.post(
    f"{API}/v1/decisions",
    headers={"Authorization": f"Bearer {TOKEN}"},
    json={"ticker": "AAPL", "debate_rounds": 2, "locale": "en"},
).json()

# Poll until done (typical 60-90s for real LLM)
while True:
    r = requests.get(
        f"{API}/v1/decisions/job/{job['job_id']}",
        headers={"Authorization": f"Bearer {TOKEN}"},
    ).json()
    if r["status"] == "done":
        break
    if r["status"] == "error":
        raise RuntimeError(r["error"])
    time.sleep(2)

decision = r["result"]["decision"]
print(decision["side"], decision["target_weight"], decision["confidence"])`;

const SAMPLE_CURL = `curl -X POST https://trading-agents-platform.onrender.com/v1/decisions \\
  -H "Authorization: Bearer sk_xxx" \\
  -H "Content-Type: application/json" \\
  -d '{"ticker": "AAPL", "debate_rounds": 2}'`;

export default function DevelopersPage() {
  const { t, locale } = useT();
  return (
    <div className="max-w-4xl mx-auto px-6 py-12 space-y-10">
      <header>
        <span className="label-cap">{t("dev.label")}</span>
        <h1 className="text-3xl font-semibold mt-1 leading-tight">{t("dev.heading")}</h1>
        <p className="text-sm text-ink-secondary mt-3 max-w-2xl leading-relaxed">
          {t("dev.subheading")}
        </p>
      </header>

      {/* What you get */}
      <section className="grid sm:grid-cols-3 gap-3">
        <Tile icon={<Code2 className="w-4 h-4" />} title="JSON REST API" body="Same endpoints as our frontend uses. POST /v1/decisions returns a job id; poll /v1/decisions/job/{id} until done." />
        <Tile icon={<KeyRound className="w-4 h-4" />} title="Bearer token auth" body="One key per app. Rate-limited per key. Revocable. Self-serve console (coming) shows usage + remaining quota." />
        <Tile icon={<Sparkles className="w-4 h-4" />} title="Real LLM" body="Gemini 3.1 Pro / DeepSeek V4 / Claude Sonnet auto-fallback. Cached repeats are free — re-asking the same ticker on the same day costs you 0 credits." />
      </section>

      {/* Quick-start code */}
      <section>
        <h2 className="text-lg font-semibold mb-3">{t("dev.docs.intro")}</h2>
        <div className="surface p-0 overflow-hidden">
          <pre className="text-xs text-ink-secondary font-mono leading-relaxed p-5 overflow-x-auto bg-bg-base">
{SAMPLE_PYTHON}
          </pre>
        </div>
        <h3 className="text-sm font-semibold mt-6 mb-2">…or just curl</h3>
        <div className="surface p-0 overflow-hidden">
          <pre className="text-xs text-ink-secondary font-mono leading-relaxed p-5 overflow-x-auto bg-bg-base">
{SAMPLE_CURL}
          </pre>
        </div>
      </section>

      {/* Bus integration story — paper §10.3, added per audit. */}
      <BusRegisterExample />

      {/* Pricing recap */}
      <section className="surface-elev p-6 flex flex-col sm:flex-row gap-4 items-start">
        <div className="flex-1">
          <h2 className="text-lg font-semibold mb-1">$99 / month</h2>
          <p className="text-sm text-ink-secondary leading-relaxed">
            500 fresh decisions/month · cached repeats free · all 6 LLM providers
            with auto-fallback · 10 req/min rate limit · email support.
          </p>
          <p className="text-xs text-ink-tertiary mt-2">
            {locale === "zh" ? "需要更多？" : "Need more?"}{" "}
            <Link href="/pricing#team" className="text-accent hover:underline">
              {locale === "zh" ? "Team / 机构方案" : "Team / institutional"}
            </Link>
          </p>
        </div>
        <Link href="/pricing#pro" className="btn-primary self-start">
          <ArrowRight className="w-4 h-4" />
          {t("dev.cta")}
        </Link>
      </section>

      <section className="text-xs text-ink-tertiary">
        <p>
          The full OpenAPI schema is auto-generated by FastAPI at{" "}
          <a
            href={`${process.env.NEXT_PUBLIC_API || ""}/docs`}
            target="_blank" rel="noopener noreferrer"
            className="text-accent hover:underline font-mono"
          >
            /docs
          </a>{" "}
          (interactive Swagger UI). Source on{" "}
          <a
            href="https://github.com/gallen666/trading-agents-platform"
            target="_blank" rel="noopener noreferrer"
            className="text-accent hover:underline"
          >
            GitHub
          </a>{" "}
          if you want to self-host instead.
        </p>
      </section>
    </div>
  );
}

function Tile({ icon, title, body }: { icon: React.ReactNode; title: string; body: string }) {
  return (
    <div className="surface p-4">
      <div className="flex items-center gap-2 text-ink-tertiary">{icon}<span className="label-cap">{title}</span></div>
      <p className="mt-2 text-sm text-ink-secondary leading-relaxed">{body}</p>
    </div>
  );
}
