import { ShieldAlert } from "lucide-react";

export default function Disclaimer() {
  return (
    <div className="max-w-2xl mx-auto px-6 py-12">
      <div className="flex items-center gap-3 mb-6">
        <div className="w-10 h-10 rounded-lg bg-signal-warn_soft text-signal-warn flex items-center justify-center">
          <ShieldAlert className="w-5 h-5" />
        </div>
        <h1 className="text-2xl font-semibold">Disclaimer</h1>
      </div>

      <div className="space-y-5 text-ink-secondary leading-relaxed">
        <p>
          <strong className="text-ink-primary">
            TradingAgents is a research and decision-support tool.
          </strong>{" "}
          Outputs are generated by large language models analyzing public market
          data. They are not investment advice, not personal recommendations,
          and not solicitations to buy or sell any security.
        </p>
        <p>
          Markets are unpredictable. Past performance — including any backtest
          shown in this product — is not indicative of future results. The
          system can be wrong, and the agents may produce confidently-incorrect
          analysis.
        </p>
        <p>
          You are solely responsible for any trading decisions you make. Consult
          a licensed advisor before acting on any output of this system.
        </p>
        <p>
          TradingAgents does not execute trades on your behalf. We do not hold
          custody of any funds.
        </p>
        <p>
          Inputs you submit (tickers, notes) and the resulting analyses are
          stored under your account for product functionality. We do not sell
          or share your data with third parties.
        </p>
      </div>
    </div>
  );
}
