export default function Disclaimer() {
  return (
    <div style={{ maxWidth: 720, lineHeight: 1.6 }}>
      <h2>Disclaimer</h2>
      <p>
        TradingAgents is a research and decision-support tool. Outputs are
        generated by large language models analyzing public market data. They
        are <strong>not investment advice</strong>, <strong>not personal
        recommendations</strong>, and <strong>not solicitations</strong> to buy
        or sell any security.
      </p>
      <p>
        Markets are unpredictable. Past performance — including any backtest
        shown in this product — is not indicative of future results. The
        system can be wrong, and the agents may produce confidently-incorrect
        analysis.
      </p>
      <p>
        You are solely responsible for any trading decisions you make. Consult
        a licensed advisor before acting on any output of this system.
      </p>
      <p>
        TradingAgents does not execute trades on your behalf. We do not hold
        custody of any funds.
      </p>
    </div>
  );
}
