"use client";

/**
 * /blog/daily/[date] — auto-generated market commentary.
 *
 * Fetches from /v1/daily-brief/{date} which is populated nightly by the
 * `/v1/cron/daily-brief` endpoint. Renders the markdown body as raw HTML
 * (the LLM output we trust to render with simple structure). 404 → friendly
 * "not generated yet" page with a CTA back to the blog index.
 */

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, Calendar, Cpu } from "lucide-react";

const API_BASE = process.env.NEXT_PUBLIC_API || "http://localhost:8000";

interface Brief {
  date: string;
  title: string;
  body_md: string;
  locale: string;
  generated_at: number;
  model: string;
}

export default function DailyBriefPage() {
  const params = useParams();
  const dateStr = (params?.date as string) || "";
  const [brief, setBrief] = useState<Brief | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [locale, setLocale] = useState<"zh" | "en">("zh");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!dateStr) return;
    setLoading(true);
    fetch(`${API_BASE}/v1/daily-brief/${encodeURIComponent(dateStr)}?locale=${locale}`)
      .then(async (r) => {
        if (!r.ok) throw new Error(`${r.status}`);
        return r.json();
      })
      .then((d: Brief) => setBrief(d))
      .catch((e) => setError(String(e)))
      .finally(() => setLoading(false));
  }, [dateStr, locale]);

  return (
    <article className="max-w-3xl mx-auto px-6 py-10">
      <Link
        href="/blog"
        className="inline-flex items-center text-sm text-foreground/60 hover:text-gold mb-6"
      >
        <ArrowLeft className="w-4 h-4 mr-1" /> All posts
      </Link>

      {loading && (
        <div className="surface p-8 text-center text-ink-secondary">Loading…</div>
      )}

      {!loading && error && <NotYet date={dateStr} />}

      {!loading && brief && (
        <>
          <header className="mb-8">
            <div className="kicker mb-2">
              {locale === "zh" ? "AI 自动生成 · 每日早评" : "Daily AI Brief"}
            </div>
            <h1 className="display text-3xl md:text-4xl text-ink-primary mb-4 leading-tight tracking-tighter">
              {brief.title}
            </h1>
            <div className="flex items-center gap-4 text-xs text-ink-tertiary font-mono">
              <span className="inline-flex items-center gap-1">
                <Calendar className="w-3.5 h-3.5" /> {brief.date.split(":")[0]}
              </span>
              <span className="inline-flex items-center gap-1">
                <Cpu className="w-3.5 h-3.5" /> {brief.model || "auto"}
              </span>
              <button
                className="ml-auto px-2 py-0.5 rounded border border-border-subtle hover:border-gold/40 text-2xs uppercase tracking-wider"
                onClick={() => setLocale(locale === "zh" ? "en" : "zh")}
              >
                {locale === "zh" ? "EN" : "中"}
              </button>
            </div>
          </header>

          {/* Render the markdown body. We trust the LLM output to be safe
              markdown — strip tags conservatively before innerHTML. */}
          <div
            className="prose prose-invert max-w-none text-ink-primary/90 leading-relaxed"
            dangerouslySetInnerHTML={{ __html: markdownToHtml(brief.body_md) }}
          />

          <footer className="mt-16 pt-8 border-t border-border-subtle text-xs text-ink-tertiary font-mono">
            {locale === "zh"
              ? "本评论由 AI 自动生成，仅作信息参考，不构成投资建议。"
              : "Generated by AI for informational purposes only. Not investment advice."}
          </footer>
        </>
      )}
    </article>
  );
}

function NotYet({ date }: { date: string }) {
  return (
    <div className="surface-elev p-10 text-center">
      <div className="kicker mb-3 justify-center">No brief yet</div>
      <h1 className="display text-2xl md:text-3xl text-ink-primary mb-3 tracking-tighter">
        No commentary generated for {date}.
      </h1>
      <p className="text-ink-secondary text-sm leading-relaxed mb-6 max-w-md mx-auto">
        Daily briefs are auto-generated by cron every morning at 06:30 UTC.
        This date either hasn&apos;t been processed yet, or the cron failed.
      </p>
      <Link href="/blog" className="btn-secondary text-sm">
        ← Back to blog
      </Link>
    </div>
  );
}

/**
 * Minimal markdown → HTML for trusted LLM output. Handles h1/h2/h3, bullets,
 * bold/italic, paragraphs. Not a full parser — the LLM is instructed to use
 * a limited subset.
 */
function markdownToHtml(md: string): string {
  const escape = (s: string) =>
    s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  const lines = md.split("\n");
  const out: string[] = [];
  let inList = false;
  let inPara = false;
  const flushPara = () => {
    if (inPara) { out.push("</p>"); inPara = false; }
  };
  const flushList = () => {
    if (inList) { out.push("</ul>"); inList = false; }
  };
  for (const raw of lines) {
    const line = raw.trim();
    if (!line) { flushPara(); flushList(); continue; }
    if (/^#\s/.test(line)) {
      flushPara(); flushList();
      out.push(`<h1 class="display text-3xl mt-8 mb-4 text-ink-primary tracking-tighter">${inline(escape(line.slice(2)))}</h1>`);
      continue;
    }
    if (/^##\s/.test(line)) {
      flushPara(); flushList();
      out.push(`<h2 class="display text-2xl mt-8 mb-3 text-ink-primary tracking-tighter">${inline(escape(line.slice(3)))}</h2>`);
      continue;
    }
    if (/^###\s/.test(line)) {
      flushPara(); flushList();
      out.push(`<h3 class="text-lg font-semibold mt-6 mb-2 text-ink-primary">${inline(escape(line.slice(4)))}</h3>`);
      continue;
    }
    if (/^[-*]\s/.test(line)) {
      flushPara();
      if (!inList) { out.push(`<ul class="list-disc ml-6 mb-4 space-y-2">`); inList = true; }
      out.push(`<li>${inline(escape(line.slice(2)))}</li>`);
      continue;
    }
    flushList();
    if (!inPara) { out.push(`<p class="mb-4 leading-relaxed">`); inPara = true; }
    else out.push(" ");
    out.push(inline(escape(line)));
  }
  flushPara(); flushList();
  return out.join("");
}

function inline(s: string): string {
  return s
    .replace(/\*\*(.+?)\*\*/g, "<strong class='text-gold'>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/`(.+?)`/g, "<code class='font-mono text-accent text-[0.9em] px-1 py-0.5 rounded bg-bg-subtle'>$1</code>");
}
